"""empty message

Revision ID: 53720a304cd9
Revises: 
Create Date: 2024-01-07 22:29:26.893609

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53720a304cd9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('otp', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('otp')

    # ### end Alembic commands ###
